name: "Run tests"

on:
  push:
    paths:
      - 'mlops-project-26/.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'mlops-project-26/.github/workflows/tests.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
